"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username$hostname$directory$git_branch$git_status$nodejs$python$golang$rust$docker_context$cmd_duration
$character"""

palette = "catppuccin_mocha"

[character]
success_symbol = "[❯](green) "
error_symbol = "[❯](red) "
vimcmd_symbol = "[❮](subtext1)"

[username]
style_user = "bold peach"
style_root = "bold red"
format = "[$user]($style)@"
show_always = false

[hostname]
ssh_only = true
style = "bold peach"
format = "[$hostname]($style) "
disabled = false

[directory]
truncation_length = 4
style = "bold lavender"
format = "[$path]($style)[$read_only]($read_only_style) "
read_only = " 󰌾"

[git_branch]
style = "bold mauve"
format = "[$symbol$branch]($style) "
symbol = " "

[git_status]
style = "bold peach"
format = "([$all_status$ahead_behind]($style)) "

[nodejs]
style = "bold green"
format = "[$symbol($version )]($style)"

[python]
style = "bold yellow"
format = "[$symbol($version )]($style)"

[golang]
style = "bold sapphire"
format = "[$symbol($version )]($style)"

[rust]
style = "bold maroon"
format = "[$symbol($version )]($style)"

[docker_context]
style = "bold sky"
format = "[$symbol$context]($style) "

[cmd_duration]
style = "bold overlay1"
format = "took [$duration]($style) "
min_time = 2_000

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
